# Generated by Django 3.0.5 on 2021-09-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_auto_20210924_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='available_colours',
            field=models.ManyToManyField(to='cart.ColourVariation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='available_sizes',
            field=models.ManyToManyField(to='cart.SizeVariation'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(to='cart.ColourVariation'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(to='cart.SizeVariation'),
        ),
    ]
