# Generated by Django 3.0.5 on 2021-09-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210924_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='available_colours',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colour',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='cart.ColourVariation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='cart.SizeVariation'),
            preserve_default=False,
        ),
    ]
